In [39]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.svm import SVC
from collections import Counter
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [40]:
df = pd.read_csv('trainingdata-all-annotations.csv')

 Instead of directly taking the tweets, I'm preprocessing the tweets

In [41]:
# maximal preprocessing step 
tweets = df['Tweet'] 
changed_tweet = []
for k in tweets:
    a = []
    for i in k.split():
        if i[0] != '@' and i[0] !='#':
            print(i)
            a.append(i)
    temp = (' '.join(a)).lower()
    changed_tweet.append(temp)

dear
lord
thank
u
for
all
of
ur
blessings
forgive
my
sins
lord
give
me
strength
and
energy
for
this
busy
day
ahead
Blessed
are
the
peacemakers,
for
they
shall
be
called
children
of
God.
Matthew
5:9
I
am
not
conformed
to
this
world.
I
am
transformed
by
the
renewing
of
my
mind.
Salah
should
be
prayed
with
and
warns
against
prayers
done
just
for
Surah
Al-Maoon
107:4-6
And
stay
in
your
houses
and
do
not
display
yourselves
like
that
of
the
times
of
ignorance."
[Quran
33:33].#islam
If
we
are
unsure
whether
something
is
halal
or
haram,
we
should
leave
it
-
this
will
our
Papa
God,
i
pray
that
You
shower
me
with
more
patience.
Now
that
the
SCOC
has
ruled
Canadians
have
freedom
from
religion,
can
someone
tell
Harper
to
dummy
his
'god
bless
Canada'.
Wow,
unsubstantiated
claims
about
spooks.
Remember
whe
I
said
there
were
gullible
people?
RT
"...That
kind
of
modesty
is
too
arrogant
for
me."Õ¢ëÑëÓChristopher
Hitchens
2/2"
Everyone
is
able
to
believe
in
whatever
they
want.
The
best
of
you
are
those


In [42]:
changed_tweet

['dear lord thank u for all of ur blessings forgive my sins lord give me strength and energy for this busy day ahead',
 'blessed are the peacemakers, for they shall be called children of god. matthew 5:9',
 'i am not conformed to this world. i am transformed by the renewing of my mind.',
 'salah should be prayed with and warns against prayers done just for surah al-maoon 107:4-6',
 'and stay in your houses and do not display yourselves like that of the times of ignorance." [quran 33:33].#islam',
 'if we are unsure whether something is halal or haram, we should leave it - this will our',
 'papa god, i pray that you shower me with more patience.',
 "now that the scoc has ruled canadians have freedom from religion, can someone tell harper to dummy his 'god bless canada'.",
 'wow, unsubstantiated claims about spooks. remember whe i said there were gullible people?',
 'rt "...that kind of modesty is too arrogant for me."õ¢ëñëóchristopher hitchens 2/2"',
 'everyone is able to believe in what

In [43]:
df['max_preprocess'] = changed_tweet
allTweets = "".join(df['max_preprocess'])
words = allTweets.split()
word_counts = Counter(words)
most_common_words = word_counts.most_common(70)

In [44]:
stop_words = []
for i in most_common_words:
    stop_words.append(i[0])
print(stop_words)

['the', 'to', 'a', 'of', 'is', 'and', 'in', 'you', 'for', 'i', 'be', 'that', 'are', 'not', 'on', 'have', 'it', 'with', 'we', 'your', 'my', '&', 'will', 'this', 'as', 'all', 'but', 'about', 'they', "don't", 'can', 'who', 'so', 'at', 'just', 'if', 'what', 'no', 'or', 'do', 'their', 'me', 'like', 'people', 'by', 'get', 'has', 'when', 'women', 'more', 'how', "it's", 'her', 'from', 'an', 'our', 'out', 'want', 'he', 'she', 'up', 'need', 'one', '-', 'know', 'right', 'should', 'make', "i'm", "can't"]


In [45]:
filtered_sent = []
for k in df['max_preprocess']:
    filtered_words = []
    for i in k.split():
        if i not in stop_words:
            filtered_words.append(i)
    filtered_sent.append(' '.join(filtered_words))

In [46]:
df['final_preprocessed_data'] = filtered_sent

In [47]:
df

ID                    Target  \
0      101                   Atheism   
1      102                   Atheism   
2      103                   Atheism   
3      104                   Atheism   
4      105                   Atheism   
...    ...                       ...   
2809  2910  Legalization of Abortion   
2810  2911  Legalization of Abortion   
2811  2912  Legalization of Abortion   
2812  2913  Legalization of Abortion   
2813  2914  Legalization of Abortion   

                                                  Tweet   Stance  \
0     dear lord thank u for all of ur blessings forg...  AGAINST   
1     Blessed are the peacemakers, for they shall be...  AGAINST   
2     I am not conformed to this world. I am transfo...  AGAINST   
3     Salah should be prayed with #focus and #unders...  AGAINST   
4     And stay in your houses and do not display you...  AGAINST   
...                                                 ...      ...   
2809  There's a law protecting unborn eagles, but no...  AGAINST   
2810  I am 1 in 3... I have had an abortion #Abortio...  AGAINST   
2811  How dare you say my sexual preference is a cho...  AGAINST   
2812  Equal rights for those 'born that way', no rig...  AGAINST   
2813  #POTUS seals his legacy w/ 1/2 doz wins. The #...  AGAINST   

     Opinion towards Sentiment  \
0              OTHER  POSITIVE   
1              OTHER  POSITIVE   
2              OTHER  POSITIVE   
3              OTHER  POSITIVE   
4              OTHER  NEGATIVE   
...              ...       ...   
2809          TARGET  NEGATIVE   
2810           OTHER   NEITHER   
2811           OTHER  NEGATIVE   
2812           OTHER  NEGATIVE   
2813           OTHER  NEGATIVE   

                                         max_preprocess  \
0     dear lord thank u for all of ur blessings forg...   
1     blessed are the peacemakers, for they shall be...   
2     i am not conformed to this world. i am transfo...   
3     salah should be prayed with and warns against ...   
4     and stay in your houses and do not display you...   
...                                                 ...   
2809  there's a law protecting unborn eagles, but no...   
2810              i am 1 in 3... i have had an abortion   
2811  how dare you say my sexual preference is a cho...   
2812  equal rights for those 'born that way', no rig...   
2813  seals his legacy w/ 1/2 doz wins. the agenda? ...   

                                final_preprocessed_data  
0     dear lord thank u ur blessings forgive sins lo...  
1     blessed peacemakers, shall called children god...  
2     am conformed world. am transformed renewing mind.  
3     salah prayed warns against prayers done surah ...  
4     stay houses display yourselves times ignorance...  
...                                                 ...  
2809  there's law protecting unborn eagles, humans u...  
2810                             am 1 3... had abortion  
2811  dare say sexual preference choice, dare say di...  
2812  equal rights those 'born way', rights those ye...  
2813  seals his legacy w/ 1/2 doz wins. agenda? stil...  

[2814 rows x 8 columns]

In [48]:
df

ID                    Target  \
0      101                   Atheism   
1      102                   Atheism   
2      103                   Atheism   
3      104                   Atheism   
4      105                   Atheism   
...    ...                       ...   
2809  2910  Legalization of Abortion   
2810  2911  Legalization of Abortion   
2811  2912  Legalization of Abortion   
2812  2913  Legalization of Abortion   
2813  2914  Legalization of Abortion   

                                                  Tweet   Stance  \
0     dear lord thank u for all of ur blessings forg...  AGAINST   
1     Blessed are the peacemakers, for they shall be...  AGAINST   
2     I am not conformed to this world. I am transfo...  AGAINST   
3     Salah should be prayed with #focus and #unders...  AGAINST   
4     And stay in your houses and do not display you...  AGAINST   
...                                                 ...      ...   
2809  There's a law protecting unborn eagles, but no...  AGAINST   
2810  I am 1 in 3... I have had an abortion #Abortio...  AGAINST   
2811  How dare you say my sexual preference is a cho...  AGAINST   
2812  Equal rights for those 'born that way', no rig...  AGAINST   
2813  #POTUS seals his legacy w/ 1/2 doz wins. The #...  AGAINST   

     Opinion towards Sentiment  \
0              OTHER  POSITIVE   
1              OTHER  POSITIVE   
2              OTHER  POSITIVE   
3              OTHER  POSITIVE   
4              OTHER  NEGATIVE   
...              ...       ...   
2809          TARGET  NEGATIVE   
2810           OTHER   NEITHER   
2811           OTHER  NEGATIVE   
2812           OTHER  NEGATIVE   
2813           OTHER  NEGATIVE   

                                         max_preprocess  \
0     dear lord thank u for all of ur blessings forg...   
1     blessed are the peacemakers, for they shall be...   
2     i am not conformed to this world. i am transfo...   
3     salah should be prayed with and warns against ...   
4     and stay in your houses and do not display you...   
...                                                 ...   
2809  there's a law protecting unborn eagles, but no...   
2810              i am 1 in 3... i have had an abortion   
2811  how dare you say my sexual preference is a cho...   
2812  equal rights for those 'born that way', no rig...   
2813  seals his legacy w/ 1/2 doz wins. the agenda? ...   

                                final_preprocessed_data  
0     dear lord thank u ur blessings forgive sins lo...  
1     blessed peacemakers, shall called children god...  
2     am conformed world. am transformed renewing mind.  
3     salah prayed warns against prayers done surah ...  
4     stay houses display yourselves times ignorance...  
...                                                 ...  
2809  there's law protecting unborn eagles, humans u...  
2810                             am 1 3... had abortion  
2811  dare say sexual preference choice, dare say di...  
2812  equal rights those 'born way', rights those ye...  
2813  seals his legacy w/ 1/2 doz wins. agenda? stil...  

[2814 rows x 8 columns]

In [49]:
processed_tweets = df['final_preprocessed_data']

In [50]:
processed_tweets 

0       dear lord thank u ur blessings forgive sins lo...
1       blessed peacemakers, shall called children god...
2       am conformed world. am transformed renewing mind.
3       salah prayed warns against prayers done surah ...
4       stay houses display yourselves times ignorance...
                              ...                        
2809    there's law protecting unborn eagles, humans u...
2810                               am 1 3... had abortion
2811    dare say sexual preference choice, dare say di...
2812    equal rights those 'born way', rights those ye...
2813    seals his legacy w/ 1/2 doz wins. agenda? stil...
Name: final_preprocessed_data, Length: 2814, dtype: object

Encoding the labels

In [51]:


label_encoder = preprocessing.LabelEncoder()

df['Sentiment_encoded'] = label_encoder.fit_transform(df['Sentiment'])

In [52]:
print(df['Sentiment_encoded'].unique())
print(df['Sentiment'].unique())

[2 0 1]
['POSITIVE' 'NEGATIVE' 'NEITHER']


In [53]:
df[['Sentiment', 'Sentiment_encoded']]

Sentiment  Sentiment_encoded
0     POSITIVE                  2
1     POSITIVE                  2
2     POSITIVE                  2
3     POSITIVE                  2
4     NEGATIVE                  0
...        ...                ...
2809  NEGATIVE                  0
2810   NEITHER                  1
2811  NEGATIVE                  0
2812  NEGATIVE                  0
2813  NEGATIVE                  0

[2814 rows x 2 columns]

In [54]:


X = df['final_preprocessed_data']
y = df['Sentiment_encoded']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

vectorizer = CountVectorizer()

X_train_counts = vectorizer.fit_transform(X_train)

X_test_counts = vectorizer.transform(X_test)

In [55]:
df

ID                    Target  \
0      101                   Atheism   
1      102                   Atheism   
2      103                   Atheism   
3      104                   Atheism   
4      105                   Atheism   
...    ...                       ...   
2809  2910  Legalization of Abortion   
2810  2911  Legalization of Abortion   
2811  2912  Legalization of Abortion   
2812  2913  Legalization of Abortion   
2813  2914  Legalization of Abortion   

                                                  Tweet   Stance  \
0     dear lord thank u for all of ur blessings forg...  AGAINST   
1     Blessed are the peacemakers, for they shall be...  AGAINST   
2     I am not conformed to this world. I am transfo...  AGAINST   
3     Salah should be prayed with #focus and #unders...  AGAINST   
4     And stay in your houses and do not display you...  AGAINST   
...                                                 ...      ...   
2809  There's a law protecting unborn eagles, but no...  AGAINST   
2810  I am 1 in 3... I have had an abortion #Abortio...  AGAINST   
2811  How dare you say my sexual preference is a cho...  AGAINST   
2812  Equal rights for those 'born that way', no rig...  AGAINST   
2813  #POTUS seals his legacy w/ 1/2 doz wins. The #...  AGAINST   

     Opinion towards Sentiment  \
0              OTHER  POSITIVE   
1              OTHER  POSITIVE   
2              OTHER  POSITIVE   
3              OTHER  POSITIVE   
4              OTHER  NEGATIVE   
...              ...       ...   
2809          TARGET  NEGATIVE   
2810           OTHER   NEITHER   
2811           OTHER  NEGATIVE   
2812           OTHER  NEGATIVE   
2813           OTHER  NEGATIVE   

                                         max_preprocess  \
0     dear lord thank u for all of ur blessings forg...   
1     blessed are the peacemakers, for they shall be...   
2     i am not conformed to this world. i am transfo...   
3     salah should be prayed with and warns against ...   
4     and stay in your houses and do not display you...   
...                                                 ...   
2809  there's a law protecting unborn eagles, but no...   
2810              i am 1 in 3... i have had an abortion   
2811  how dare you say my sexual preference is a cho...   
2812  equal rights for those 'born that way', no rig...   
2813  seals his legacy w/ 1/2 doz wins. the agenda? ...   

                                final_preprocessed_data  Sentiment_encoded  
0     dear lord thank u ur blessings forgive sins lo...                  2  
1     blessed peacemakers, shall called children god...                  2  
2     am conformed world. am transformed renewing mind.                  2  
3     salah prayed warns against prayers done surah ...                  2  
4     stay houses display yourselves times ignorance...                  0  
...                                                 ...                ...  
2809  there's law protecting unborn eagles, humans u...                  0  
2810                             am 1 3... had abortion                  1  
2811  dare say sexual preference choice, dare say di...                  0  
2812  equal rights those 'born way', rights those ye...                  0  
2813  seals his legacy w/ 1/2 doz wins. agenda? stil...                  0  

[2814 rows x 9 columns]

In [56]:

SVM = SVC(kernel='linear', decision_function_shape ='ovr')
SVM.fit(X_train_counts, y_train, )
predictions = SVM.predict(X_test_counts)
acc_score = (accuracy_score(y_test, predictions)*100)
print("Accuracy score for SVM: \n ", acc_score, "\n")
conf_mat = (confusion_matrix(y_test, predictions))
print('Confusion matrix for SVM: \n', conf_mat , '\n')
clf_report = classification_report(y_test, predictions)
print("Classification Report for SVM: \n", clf_report, '\n')


Accuracy score for SVM: 
  69.09413854351686 

Confusion matrix for SVM: 
 [[268   6  66]
 [ 26   4   7]
 [ 63   6 117]] 

Classification Report for SVM: 
               precision    recall  f1-score   support

           0       0.75      0.79      0.77       340
           1       0.25      0.11      0.15        37
           2       0.62      0.63      0.62       186

    accuracy                           0.69       563
   macro avg       0.54      0.51      0.51       563
weighted avg       0.67      0.69      0.68       563
 



In [57]:
with open("output.txt", "w") as f:
    f.write(f"Accuracy score for SVM: \n  {acc_score} \n \n Confusion matrix for SVM: \n {conf_mat}  \n \nClassification Report for SVM: \n {clf_report} \n")
f.close()
